// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentGradingProgram.Model;

#nullable disable

namespace StudentGradingProgram.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427194323_ExamTableColumnsHeading_added")]
    partial class ExamTableColumnsHeading_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("StudentGradingProgram.Model.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("StudentGradingProgram.Model.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("StudentGradingProgram.Model.ExamScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Score1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Score2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Score3")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Score4")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Score5")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentID");

                    b.ToTable("ExamScores");
                });

            modelBuilder.Entity("StudentGradingProgram.Model.ExamTableColumnsHeading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Header1Name")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Header2Name")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Header3Name")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Header4Name")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Header5Name")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamTableColumnsHeadings");
                });

            modelBuilder.Entity("StudentGradingProgram.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentGradingProgram.Model.ExamScore", b =>
                {
                    b.HasOne("StudentGradingProgram.Model.Exam", "Exam")
                        .WithMany("ExamScores")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentGradingProgram.Model.Student", "Student")
                        .WithMany("ExamScores")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentGradingProgram.Model.ExamTableColumnsHeading", b =>
                {
                    b.HasOne("StudentGradingProgram.Model.Exam", "Exam")
                        .WithMany("ExamTableColumnsHeadings")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("StudentGradingProgram.Model.Student", b =>
                {
                    b.HasOne("StudentGradingProgram.Model.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("StudentGradingProgram.Model.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentGradingProgram.Model.Exam", b =>
                {
                    b.Navigation("ExamScores");

                    b.Navigation("ExamTableColumnsHeadings");
                });

            modelBuilder.Entity("StudentGradingProgram.Model.Student", b =>
                {
                    b.Navigation("ExamScores");
                });
#pragma warning restore 612, 618
        }
    }
}
